### ISSUE TITLE
Life Counter

### ISSUE THREAD

**Issue by dav5037** [dav5037/MtgPal#1]
The Life Counter should consist of two vertical "health bars" and a number read out for life points. Also necessary are two pairs of up and down buttons for increasing or decreasing the amount of life. Lastly, a return/main menu button should be included to return to the main menu.

**Comment by akoehler94** [comment]
The Life Counter should consist of two vertical "health bars" and a number read out for life points. Also necessary are two pairs of up and down buttons for increasing or decreasing the amount of life. Lastly, a return/main menu button should be included to return to the main menu.

**Comment by akoehler94** [comment]
Minimal working Life Counter (no fancy GUI)
