### ISSUE TITLE
Dice Simulator

### ISSUE THREAD

**Issue by dav5037** [dav5037/MtgPal#2]
The Dice Simulator will essentially be a random number generator bounded from either 1-6 or 1-20 that is stylized for Magic the Gathering. Also appearing on the page is a button to choose which die to role (d6 or d20), and return/main menu button.

**Comment by akoehler94** [comment]
The Dice Simulator will essentially be a random number generator bounded from either 1-6 or 1-20 that is stylized for Magic the Gathering. Also appearing on the page is a button to choose which die to role (d6 or d20), and return/main menu button.

**Comment by dav5037** [comment]
Basic version implemented
